### PR TITLE
Add GH stars count to plugins

### PR DESCRIPTION
**Pull request by sylvainpolletvillard**
Hi,

I noticed that the number of Github stars was available in the data but not displayed in the website. I think it is valuable information so I add it this way:

image

Feel free to update the styles to your convenience of course

### CODE REVIEW

**Comment by himynameisdave** [comment]
@sylvainpolletvillard this is rad, thanks for adding!

**Comment by himynameisdave** [comment]
It's important to know that the stars on the plugins list are only updated periodically, so it won't be perfectly up-to-date in every case.

Just thought you should be aware, still a big fan of having this feature in there though 👍

**Comment by sylvainpolletvillard** [comment]
Yeah I saw you there: https://github.com/himynameisdave/postcss-plugins/blob/master/scripts/updateStars.js

Maybe there is a way to automate it further so that you don't have to run the script and push the updates every time, like a crontab for github. Anyway if this is done everytime a plugin is added, I suppose it is good enough currently.

**Comment by himynameisdave** [comment]
Yeah like it should be fine for a rough estimate, but later if we wanted we could hit the GitHub API for the actual ⭐️ count 👍

**Review by mxstbr — APPROVED** [review]
This is great, thanks!

**Comment by mxstbr** [comment]
Sorry for merging this so slowly, I've forgotten where I deployed the site 😅  I'm moving it to Netlify now so the `master` branch gets auto-deployed :muscle:

**Comment by himynameisdave** [comment]
@mxstbr lol don't worry about it dude, you're busy [pimping `styled-components`](https://youtu.be/2j9rSur_mnk) to the world! 👍 💅  Great talk, btw!

**Pull request merged**
