### PR TITLE
Convert everything over to use webpack

### PR DESCRIPTION
**Pull request by browniefed**

### CODE REVIEW

**Comment by mxstbr** [comment]
Fresh clone and install of that branch, getting this error when starting "npm run dev":

```
ERROR in ./js/app.js
Module build failed: ReferenceError: [BABEL] postcss.parts/js/app.js: Unknown option: direct.presets
    at Logger.error (postcss.parts/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (postcss.parts/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.init (postcss.parts/node_modules/babel-core/lib/transformation/file/options/option-manager.js:216:10)
    at File.initOptions (postcss.parts/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (postcss.parts/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (postcss.parts/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (postcss.parts/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (postcss.parts/node_modules/babel-loader/index.js:88:12)
```

**Comment by browniefed** [comment]
Heh, helps if you install `babel-core`... you know the thing that does all the stuff :smile: .
I added `babel-core` to the `package.json` so it should be good to go. I actually am unsure why mine was working without it, deleted all node_modules and it still worked, odd.

**Comment by mxstbr** [comment]
It works now! :tada:

One more thing though, when building the application I get four files: bundle.js, bundle.js.map, main.min.css and main.min.css.map. Do we need the source maps for anything in production?

**Comment by browniefed** [comment]
I generate them just in case. It's not that big of a deal if we don't ship with them. They are mostly for making debugging easier in production and are only loaded if you open up the dev tools.

I say we don't need them since we aren't doing any error monitoring in prod.

**Comment by browniefed** [comment]
Just making sure you saw this. We can ditch the sourcemaps and just deploy the 2 files.

**Comment by mxstbr** [comment]
Oh sorry, no I think it's fine, thanks! I'll merge and deploy asap!

**Comment by mxstbr** [comment]
Thanks for pinging me again, I saw the notification but didn't act on it and forgot. :blush: my bad!

**Pull request merged**
